// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaRKmPKjMUIZZSS56rl7Skv7ErHUjOydo',
    appId: '1:12530160530:web:2270c81c21bde72a7aa74b',
    messagingSenderId: '12530160530',
    projectId: 'sabertooth-donut',
    authDomain: 'sabertooth-donut.firebaseapp.com',
    storageBucket: 'sabertooth-donut.appspot.com',
    measurementId: 'G-SEGX1TNCXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4VkPu0RDh-HC8aPsR4aC_Alhow-i6aGo',
    appId: '1:12530160530:android:3251a37c0b3290287aa74b',
    messagingSenderId: '12530160530',
    projectId: 'sabertooth-donut',
    storageBucket: 'sabertooth-donut.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWjv7O730fib9FSuAUEfz3MKRe7vqfWpk',
    appId: '1:12530160530:ios:263eb0e2f9c046b97aa74b',
    messagingSenderId: '12530160530',
    projectId: 'sabertooth-donut',
    storageBucket: 'sabertooth-donut.appspot.com',
    iosBundleId: 'com.example.sabertoothDonut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWjv7O730fib9FSuAUEfz3MKRe7vqfWpk',
    appId: '1:12530160530:ios:263eb0e2f9c046b97aa74b',
    messagingSenderId: '12530160530',
    projectId: 'sabertooth-donut',
    storageBucket: 'sabertooth-donut.appspot.com',
    iosBundleId: 'com.example.sabertoothDonut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaRKmPKjMUIZZSS56rl7Skv7ErHUjOydo',
    appId: '1:12530160530:web:830643b4a8c3d2867aa74b',
    messagingSenderId: '12530160530',
    projectId: 'sabertooth-donut',
    authDomain: 'sabertooth-donut.firebaseapp.com',
    storageBucket: 'sabertooth-donut.appspot.com',
    measurementId: 'G-0HNNBZVRWW',
  );
}